image: clojure

stages:
  - test

unit-clojure:
  stage: test
  script: 
    - lein test

after_script:
- lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
