
stages:
  - docker
  - test

variables:
  build_docker: 'false'

docker-build:
  stage: docker
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest docker
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    changes:
      - docker/Dockerfile
    variables:
      - $build_docker =~ /true/i

unit-clojure:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script: 
    - ./bin/auto-test-clojure-on-push.csh

